packages:
  - "."

allowBuilds:
  '@parcel/watcher': true

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - postcss@8.5.23
  - nanoid@3.3.18

overrides:
  nanoid@<3.3.18: ^3.3.18
  postcss@<=8.5.22: ^8.5.23
